-- ============================================================
-- HomeServicesBookingDb - Database Creation Script
-- Generated from EF Core Migration: 20260504212717_InitialCreate
-- PasswordHash value read from live database (not plain text)
-- ============================================================

USE [master];
GO

-- Create database if not exists
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'HomeServicesBookingDb')
BEGIN
    CREATE DATABASE [HomeServicesBookingDb];
END
GO

USE [HomeServicesBookingDb];
GO

-- ============================================================
-- Table: Services
-- ============================================================
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Services')
BEGIN
    CREATE TABLE [Services] (
        [Id]          INT            IDENTITY (1, 1) NOT NULL,
        [Name]        NVARCHAR (150) NOT NULL,
        [Description] NVARCHAR (MAX) NOT NULL,
        [IsActive]    BIT            NOT NULL DEFAULT 1,
        [CreatedAt]   DATETIME2      NOT NULL DEFAULT SYSUTCDATETIME(),
        [UpdatedAt]   DATETIME2      NULL,

        CONSTRAINT [PK_Services] PRIMARY KEY CLUSTERED ([Id] ASC)
    );

    CREATE NONCLUSTERED INDEX [IX_Services_IsActive]
        ON [Services] ([IsActive]);
END
GO

-- ============================================================
-- Table: Orders
-- ============================================================
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Orders')
BEGIN
    CREATE TABLE [Orders] (
        [Id]           INT            IDENTITY (1, 1) NOT NULL,
        [CustomerName] NVARCHAR (150) NOT NULL,
        [Phone]        NVARCHAR (20)  NOT NULL,
        [Address]      NVARCHAR (300) NOT NULL,
        [ServiceId]    INT            NULL,
        [ServiceName]  NVARCHAR (150) NOT NULL,
        [OrderDate]    DATETIME2      NOT NULL,
        [Status]       NVARCHAR (30)  NOT NULL DEFAULT N'Pending',
        [CreatedAt]    DATETIME2      NOT NULL DEFAULT SYSUTCDATETIME(),
        [UpdatedAt]    DATETIME2      NULL,

        CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED ([Id] ASC),
        CONSTRAINT [FK_Orders_Services_ServiceId]
            FOREIGN KEY ([ServiceId]) REFERENCES [Services] ([Id])
            ON DELETE SET NULL
    );

    CREATE NONCLUSTERED INDEX [IX_Orders_CustomerName] ON [Orders] ([CustomerName]);
    CREATE NONCLUSTERED INDEX [IX_Orders_OrderDate]     ON [Orders] ([OrderDate]);
    CREATE NONCLUSTERED INDEX [IX_Orders_Phone]         ON [Orders] ([Phone]);
    CREATE NONCLUSTERED INDEX [IX_Orders_ServiceId]     ON [Orders] ([ServiceId]);
    CREATE NONCLUSTERED INDEX [IX_Orders_Status]        ON [Orders] ([Status]);
END
GO

-- ============================================================
-- Table: AdminUsers
-- ============================================================
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'AdminUsers')
BEGIN
    CREATE TABLE [AdminUsers] (
        [Id]           INT            IDENTITY (1, 1) NOT NULL,
        [Email]        NVARCHAR (150) NOT NULL,
        [PasswordHash] NVARCHAR (MAX) NOT NULL,
        [CreatedAt]    DATETIME2      NOT NULL DEFAULT SYSUTCDATETIME(),

        CONSTRAINT [PK_AdminUsers] PRIMARY KEY CLUSTERED ([Id] ASC)
    );

    CREATE UNIQUE NONCLUSTERED INDEX [IX_AdminUsers_Email]
        ON [AdminUsers] ([Email]);
END
GO

-- ============================================================
-- Seed Data
-- ============================================================

-- Default services (only if table is empty)
IF NOT EXISTS (SELECT 1 FROM [Services])
BEGIN
    INSERT INTO [Services] ([Name], [Description]) VALUES
        (N'سباكة',    N'إصلاح وصيانة أعمال السباكة المنزلية'),
        (N'كهرباء',   N'أعمال الكهرباء والتمديدات المنزلية'),
        (N'نجارة',    N'إصلاح وتصنيع الأثاث والأبواب'),
        (N'تكييف',    N'تركيب وصيانة وتنظيف أجهزة التكييف'),
        (N'دهانات',   N'أعمال الدهانات الداخلية والخارجية');
END
GO

-- Default admin user (only if not exists)
-- PasswordHash is the actual hashed value for password "Admin@123"
-- generated by ASP.NET Core PasswordHasher<AdminUser>
IF NOT EXISTS (SELECT 1 FROM [AdminUsers] WHERE [Email] = N'admin@site.com')
BEGIN
    INSERT INTO [AdminUsers] ([Email], [PasswordHash]) VALUES
        (N'admin@site.com',
         N'AQAAAAIAAYagAAAAEHHeQqfXMMLCH4KPTCGK64FesjfiRd7WgxQMtzQS+3JGSy6YkANzChSdSQeCLZnTAQ==');
END
GO
